#if UNITY_EDITOR
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.Localization.Tables;

namespace DaemonHunter.Localization.Editor
{
    /// <summary>
    /// Scans every StringTableCollection in the project and generates a
    /// strongly-typed L10nKeys.cs, so call sites never hand-type a raw key
    /// string. Re-run after adding/renaming keys in any table.
    /// </summary>
    public static class L10nKeyGenerator
    {
        private const string OutputPath = "Assets/Scripts/Localization/Generated/L10nKeys.cs";

        [MenuItem("Tools/Localization/Generate Key Constants")]
        public static void Generate()
        {
            var guids = AssetDatabase.FindAssets("t:StringTableCollection");
            var sb = new StringBuilder();

            sb.AppendLine("// AUTO-GENERATED by Tools > Localization > Generate Key Constants.");
            sb.AppendLine("// Do not edit by hand - changes will be overwritten.");
            sb.AppendLine("namespace DaemonHunter.Localization");
            sb.AppendLine("{");
            sb.AppendLine("    public static class L10nKeys");
            sb.AppendLine("    {");

            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var collection = AssetDatabase.LoadAssetAtPath<StringTableCollection>(path);
                if (collection == null) continue;

                var className = SanitizeIdentifier(collection.TableCollectionName);

                sb.AppendLine($"        /// <summary>Table: {collection.TableCollectionName}</summary>");
                sb.AppendLine($"        public static class {className}");
                sb.AppendLine("        {");
                sb.AppendLine($"            public const string TableName = \"{collection.TableCollectionName}\";");
                sb.AppendLine();

                foreach (var entry in collection.SharedData.Entries)
                {
                    var constName = SanitizeIdentifier(entry.Key);
                    sb.AppendLine($"            public const string {constName} = \"{entry.Key}\";");
                }

                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var dir = Path.GetDirectoryName(OutputPath);
            if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(OutputPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"[Localization] L10nKeys generated at {OutputPath} " +
                      $"({guids.Length} table collection(s) scanned).");
        }

        // "dialogue_daoshi_intro" -> "DialogueDaoshiIntro"
        private static string SanitizeIdentifier(string raw)
        {
            var sb = new StringBuilder();
            bool nextUpper = true;

            foreach (var c in raw)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                    nextUpper = false;
                }
                else
                {
                    nextUpper = true; // treat _ - space etc. as word boundaries
                }
            }

            var result = sb.ToString();
            if (result.Length > 0 && char.IsDigit(result[0]))
                result = "_" + result;

            return string.IsNullOrEmpty(result) ? "_Empty" : result;
        }
    }
}
#endif
